language: cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libboost-all-dev libcurl4-openssl-dev libdb5.1-dev libdb5.1++-dev libssl-dev libminiupnpc-dev libqrencode-dev libglib2.0-dev libglibmm-2.4-dev libqt4-dev python-dev qt4-dev-tools libqt4-dev libqt4-core libqt4-gui 
install:
 - cd src
 
script: 
 - make -f makefile.unix -j 5
 - cd ..
 - qmake USE_UPNP=- 
 - make -j 5
 
